### ISSUE TITLE
Exception when Calling Device.Disconnect on UWP :(

### ISSUE THREAD

**Issue by MKGNZ** [aritchie/bluetoothle#193]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - X UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
UWP only PRs?

## Version of Library
6.0.3

## Expected Behaviour
To not throw this exception.

## Suggested Fix:
In Plugin.BluetoothLE.DeviceContext.Disconnect() 
move line " this.subscribers.Clear(); " 
outside the foreach loop

[https://github.com/aritchie/bluetoothle/blob/6833c128c547daf2c30a4ca6de765a96a1b1a7d1/Plugin.BluetoothLE/Platforms/Uwp/DeviceContext.cs#L75](url)

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

 Exception: {System.InvalidOperationException: Operation is not valid due to the current state of the object.}
    Handled: false
    Message: "Collection was modified; enumeration operation may not execute."
Stack Trace:
 at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Plugin.BluetoothLE.DeviceContext.<Disconnect>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plugin.BluetoothLE.Device.<CancelConnection>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
As stated, I don’t support UWP.  You can contribute fixes if you want.  As it is, disconnect doesn’t work on UWP anyhow
