### ISSUE TITLE
[Android] Why are these exceptions thrown? Would expect timeout.

### ISSUE THREAD

**Issue by gunpuz** [aritchie/bluetoothle#281]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Expected Behaviour

Timeout exception

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Device data is not read and weird exceptions are thrown. 
Some may say that it is duplicate of #271, but the argument why #271 was closed is that you argued that device was disconnected. But as you can see here, device is not disconnected it is even paired.

![image](https://user-images.githubusercontent.com/39419120/50587342-3343d200-0e86-11e9-9476-b154e329b68e.png)

Uhh, and yeah, when this exception is thrown, seems like reconnect won't help. Reconecting and doing the same thing will instantly thow this same exception.

```
[0:] System.NullReferenceException: Object reference not set to an instance of an object.
  at Plugin.BluetoothLE.GattCharacteristic..ctor (Plugin.BluetoothLE.IGattService service, Plugin.BluetoothLE.Internals.DeviceContext context, Android.Bluetooth.BluetoothGattCharacteristic native) [0x00000] in C:\dev\acr\bluetoothle\Plugin.BluetoothLE\Platforms\Android\GattCharacteristic.cs:25
  at Plugin.BluetoothLE.GattService+<>c__DisplayClass4_0.<GetKnownCharacteristics>b__0 (System.IObserver`1[T] ob) [0x0004a] in C:\dev\acr\bluetoothle\Plugin.BluetoothLE\Platforms\Android\GattService.cs:48
  at System.Reactive.AnonymousObservable`1[T].SubscribeCore (System.IObserver`1[T] observer) [0x00000] in <370f6a6bb34048878534065376a195cb>:0
  at System.Reactive.ObservableBase`1[T].ScheduledSubscribe (System.Reactive.Concurrency.IScheduler _, System.Reactive.AutoDetachObserver`1[T] autoDetachObserver) [0x00000] in <370f6a6bb34048878534065376a195cb>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <370f6a6bb34048878534065376a195cb>:0
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <370f6a6bb34048878534065376a195cb>:0
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <370f6a6bb34048878534065376a195cb>:0
  at XXXXXXXXXXXXXXXXXXXXXX+<YYYYYYYYYYYYYYYYYYYYY>d__47.MoveNext () [0x0022f] in AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.cs:415
```

There is other case here:

![image](https://user-images.githubusercontent.com/39419120/50587022-d398f700-0e84-11e9-88e0-a62a9aeed607.png)

```
[0:] Java.Lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallBooleanMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <0ad2222fd7074badb5de547b1521aab0>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <0ad2222fd7074badb5de547b1521aab0>:0
  at Android.Bluetooth.BluetoothGatt.ReadCharacteristic (Android.Bluetooth.BluetoothGattCharacteristic characteristic) [0x00031] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0
  at Plugin.BluetoothLE.GattCharacteristic+<>c__DisplayClass8_0.<Read>b__2 () [0x00000] in C:\dev\acr\bluetoothle\Plugin.BluetoothLE\Platforms\Android\GattCharacteristic.cs:126
--- End of stack trace from previous location where exception was thrown ---
  at Plugin.BluetoothLE.Internals.DeviceContext+<>c__DisplayClass19_1`1+<<Invoke>b__1>d[T].MoveNext () [0x00057] in C:\dev\acr\bluetoothle\Plugin.BluetoothLE\Platforms\Android\Internals\DeviceContext.cs:80
--- End of stack trace from previous location where exception was thrown ---
  at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow (System.Exception exception) [0x00006] in <370f6a6bb34048878534065376a195cb>:0
  at System.Reactive.ExceptionHelpers.ThrowIfNotNull (System.Exception exception) [0x0000d] in <370f6a6bb34048878534065376a195cb>:0
  at System.Reactive.Subjects.AsyncSubject`1[T].GetResult () [0x00039] in <370f6a6bb34048878534065376a195cb>:0
  at HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH>d__40.MoveNext () [0x00160] in ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ.cs:187
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1671)
	at android.os.Parcel.readException(Parcel.java:1618)
	at android.bluetooth.IBluetoothGatt$Stub$Proxy.readCharacteristic(IBluetoothGatt.java:1022)
	at android.bluetooth.BluetoothGatt.readCharacteristic(BluetoothGatt.java:856)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

And there is this: 

```
[0:] Scheduler -> Update device: XXXXXXXX
[0:] Scheduler -> Update device: YYYYYYYY
11-16 13:51:25.794 E/BluetoothGatt(16491):
11-16 13:51:25.794 E/BluetoothGatt(16491): android.os.DeadObjectException
11-16 13:51:25.794 E/BluetoothGatt(16491): 	at android.os.BinderProxy.transactNative(Native Method)
11-16 13:51:25.794 E/BluetoothGatt(16491): 	at android.os.BinderProxy.transact(Binder.java:617)
11-16 13:51:25.794 E/BluetoothGatt(16491): 	at android.bluetooth.IBluetoothGatt$Stub$Proxy.unregisterClient(IBluetoothGatt.java:917)
11-16 13:51:25.794 E/BluetoothGatt(16491): 	at android.bluetooth.BluetoothGatt.unregisterApp(BluetoothGatt.java:620)
11-16 13:51:25.794 E/BluetoothGatt(16491): 	at android.bluetooth.BluetoothGatt.close(BluetoothGatt.java:529)
[0:] Scheduler -> Update device: ZZZZZZZZZ
```

Not sure which of these are normal and which are not, and which are bugs and which are not. Just saying that on HUAWEI tablets, data may not always be received smoothly(can be a lot of times in a row).
Keep up the good work, sorry for disturbing if these cases are totally normal. Happy new year!

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* If you have a complaint about the docs, FIX IT - DO NOT FILE IT HERE!  I won't guarantee everything is always 100% up-to-date since I am just 1 person.
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This has crossed more into a support request than an actual issue with a reproducible that I'm going to look into fixing.
