### ISSUE TITLE
Exception - The attribute requires encryption before it can be read or written. (Exception from HRESULT: 0x8065000F)

### ISSUE THREAD

**Issue by jkmandhan** [aritchie/bluetoothle#83]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [x] .NET Standard
 - [x]UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue
Windows 10 Pro version 1703

## Version of Library
5.0

## Expected Behaviour
BLE Characteristic Write/enable notification should work for peripheral device having security level "Unauthenticated pairing with encryption". It works fine for Android and iOS

## Actual Behavior
BLE Characteristic Write/enable notification throws following exception only for windows platform, for iOS and Android its working fine. I am not sure how to enable encryption before enabling notification or writing Char value?

Exception - The attribute requires encryption before it can be read or written. (Exception from HRESULT: 0x8065000F), 

StackTrace- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Plugin.BluetoothLE.GattCharacteristic.<>c__DisplayClass10_0.<<SetNotify>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by jkmandhan** [comment]
Hi Allan,
I understand this might not be supported. Could you please suggest any fix/hint for resolving this exception?
Many thanks in advance.
-Jitender

**Comment by jkmandhan** [comment]
[Code Snippet.txt](https://github.com/aritchie/bluetoothle/files/1389602/Code.Snippet.txt)
This is the code snippet where I am having the issue.
